export const PRODUCTS_DATA = [
    {
        id: 1,
        name: "Smartphone X10",
        description: "High-performance smartphone with advanced features.",
        price: 599,
        category: "Electronics",
        stock: 2,
      },
      {
        id: 2,
        name: "Men's Casual Shirt",
        description: "Comfortable and stylish shirt for casual occasions.",
        price: 39.99,
        category: "Clothing",
        stock: 3,
      },
      {
        id: 3,
        name: "JavaScript: The Good Parts",
        description: "A must-read for JavaScript enthusiasts.",
        price: 29.95,
        category: "Books",
        stock: 1,
      },
      {
        id: 4,
        name: "Yoga Mat",
        description: "High-quality yoga mat for your fitness routine.",
        price: 19.5,
        category: "Sports",
        stock: 4,
      },
      {
        id: 5,
        name: "Laptop ProBook",
        description: "Powerful laptop for professional use.",
        price: 899,
        category: "Electronics",
        stock: 0,
      },
      {
        id: 6,
        name: "Women's Sneakers",
        description: "Trendy sneakers for everyday wear.",
        price: 54.5,
        category: "Clothing",
        stock: 2,
      },
      {
        id: 7,
        name: "The Art of War",
        description: "Ancient treatise on strategy and warfare.",
        price: 15.99,
        category: "Books",
        stock: 0,
      },
      {
        id: 8,
        name: "Tennis Racket",
        description: "Professional tennis racket for improved performance.",
        price: 129.99,
        category: "Sports",
        stock: 5,
      },
      {
        id: 9,
        name: "Wireless Earbuds",
        description: "Compact earbuds with long battery life.",
        price: 79.99,
        category: "Electronics",
        stock: 2,
      },
      {
        id: 10,
        name: "Summer Dress",
        description: "Light and stylish dress for the summer season.",
        price: 29.95,
        category: "Clothing",
        stock: 1,
      },
      {
        id: 11,
        name: "Introduction to Machine Learning",
        description: "Foundational book on machine learning concepts.",
        price: 42.5,
        category: "Books",
        stock: 3,
      },
      {
        id: 12,
        name: "Bicycle Helmet",
        description: "Protective helmet for cycling enthusiasts.",
        price: 34.75,
        category: "Sports",
        stock: 4,
      },
      {
        id: 13,
        name: "Gaming Console",
        description: "Next-gen gaming console for immersive gameplay.",
        price: 449,
        category: "Electronics",
        stock: 0,
      },
      {
        id: 14,
        name: "Formal Blouse",
        description: "Elegant blouse for formal occasions.",
        price: 49.95,
        category: "Clothing",
        stock: 2,
      },
      {
        id: 15,
        name: "The Catcher in the Rye",
        description: "Classic novel by J.D. Salinger.",
        price: 9.99,
        category: "Books",
        stock: 1,
      },
      {
        id: 16,
        name: "Soccer Ball",
        description: "Durable soccer ball for practice and matches.",
        price: 19.25,
        category: "Sports",
        stock: 0,
      },
      {
        id: 17,
        name: "Bluetooth Speaker",
        description: "Portable speaker with impressive sound quality.",
        price: 69.99,
        category: "Electronics",
        stock: 5,
      },
      {
        id: 18,
        name: "Denim Jeans",
        description: "Classic denim jeans for a timeless look.",
        price: 64.95,
        category: "Clothing",
        stock: 2,
      },
      {
        id: 19,
        name: "Science Fiction Novel",
        description: "Engaging science fiction book for enthusiasts.",
        price: 12.5,
        category: "Books",
        stock: 1,
      },
      {
        id: 20,
        name: "Tennis Shoes",
        description: "High-performance tennis shoes for the court.",
        price: 89.5,
        category: "Sports",
        stock: 3,
      }
]