export const employees = [
    {
        firstName: "John",
        lastName: "Doe",
        username: "johndoe",
        email: "john.doe@example.com",
        address: {
          street: "123 Main St",
          city: "Cityville",
          zipCode: "12345",
        },
        telephoneNumber: "555-123-4567",
        position: "Software Engineer",
        salary: 90000,
        yearsOfService: 3.5,
        performance: 85,
        startDate: new Date("2020-03-15"),
      },
      {
        firstName: "Jane",
        lastName: "Smith",
        username: "janesmith",
        email: "jane.smith@example.com",
        address: {
          street: "456 Elm St",
          city: "Townton",
          zipCode: "67890",
        },
        telephoneNumber: "555-987-6543",
        position: "Data Scientist",
        salary: 75000,
        yearsOfService: 2.25,
        performance: 64,
        startDate: new Date("2021-01-10"),
      },
      {
        firstName: "Michael",
        lastName: "Johnson",
        username: "michaeljohnson",
        email: "michael.johnson@example.com",
        address: {
          street: "789 Oak Rd",
          city: "Villageville",
          zipCode: "54321",
        },
        telephoneNumber: "555-555-5555",
        position: "Software Engineer",
        salary: 80000,
        yearsOfService: 5.75,
        performance: 18,
        startDate: new Date("2018-08-22"),
      },
      {
        firstName: "Sarah",
        lastName: "Williams",
        username: "sarahwilliams",
        email: "sarah.williams@example.com",
        address: {
          street: "101 Tech Blvd",
          city: "Techville",
          zipCode: "98765",
        },
        telephoneNumber: "555-888-1234",
        position: "Software Engineer",
        salary: 85000,
        yearsOfService: 4.5,
        performance: 37,
        startDate: new Date("2019-06-18"),
      },
      {
        firstName: "David",
        lastName: "Brown",
        username: "davidbrown",
        email: "david.brown@example.com",
        address: {
          street: "222 Byte St",
          city: "Codeville",
          zipCode: "34567",
        },
        telephoneNumber: "555-777-2222",
        position: "Software Tester",
        salary: 95000,
        yearsOfService: 2.75,
        performance: 95,
        startDate: new Date("2021-04-03"),
      },
      {
        firstName: "Emily",
        lastName: "Miller",
        username: "emilymiller",
        email: "emily.miller@example.com",
        address: {
          street: "444 Code Rd",
          city: "Scripttown",
          zipCode: "56789",
        },
        telephoneNumber: "555-444-7890",
        position: "Software Tester",
        salary: 72000,
        yearsOfService: 1.5,
        performance: 68,
        startDate: new Date("2022-02-15"),
      },
      {
        firstName: "Daniel",
        lastName: "Martinez",
        username: "danielmartinez",
        email: "daniel.martinez@example.com",
        address: {
          street: "666 Bit Ave",
          city: "Logicville",
          zipCode: "12345",
        },
        telephoneNumber: "555-666-5678",
        position: "Data Scientist",
        salary: 105000,
        yearsOfService: 3.25,
        performance: 60,
        startDate: new Date("2020-09-10"),
      },
      {
        firstName: "Olivia",
        lastName: "Jones",
        username: "oliviajones",
        email: "olivia.jones@example.com",
        address: {
          street: "777 Algorithm Dr",
          city: "Functiontown",
          zipCode: "23456",
        },
        telephoneNumber: "555-123-9876",
        position: "Software Engineer",
        salary: 80000,
        yearsOfService: 2.5,
        performance: 30,
        startDate: new Date("2021-03-01"),
      },
      {
        firstName: "William",
        lastName: "Wilson",
        username: "williamwilson",
        email: "william.wilson@example.com",
        address: {
          street: "888 Code Ave",
          city: "Syntaxville",
          zipCode: "45678",
        },
        telephoneNumber: "555-777-1234",
        position: "Data Scientist",
        salary: 92000,
        yearsOfService: 6.75,
        performance: 70,
        startDate: new Date("2017-05-12"),
      },
      {
        firstName: "Sophia",
        lastName: "Davis",
        username: "sophiadavis",
        email: "sophia.davis@example.com",
        address: {
          street: "999 Script Rd",
          city: "Codeburg",
          zipCode: "56789",
        },
        telephoneNumber: "555-888-5678",
        position: "Software Engineer",
        salary: 78000,
        yearsOfService: 2,
        performance: 88,
        startDate: new Date("2021-07-20"),
      }
    ]